# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# aSpiral - Codemagic CI/CD Configuration
# Bundle ID: com.apex.aspiral
# SIGNING METHOD: Manual (using uploaded profiles)
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

workflows:
  ios-release:
    name: iOS Release to TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    environment:
      xcode: 16.4
      node: 20.19.0
      npm: 10
      cocoapods: default
      groups:
        - appstore_credentials
      vars:
        BUNDLE_ID: "com.apex.aspiral"
        XCODE_SCHEME: "App"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
      # MANUAL SIGNING - references profiles uploaded in Codemagic UI
      ios_signing:
        certificates:
          - name: aSpiral_dist_2026
        provisioning_profiles:
          - name: aSpiral_iOS_AppStoreConnect_2026
    
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'ios-v*'
          include: true
      cancel_previous_builds: true

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Run tests if present
        script: npm run test || true
        
      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor (iOS)
        script: npx cap sync ios

      - name: Set iOS version from tag + build number
        script: |
          VERSION=$(echo "$CM_TAG" | sed 's/ios-v//')
          if [ -z "$VERSION" ]; then
            VERSION="1.0.0"
          fi
          echo "APP_VERSION=$VERSION" >> $CM_ENV
          
          cd ios/App
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" 2>/dev/null || echo "0")
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          
          agvtool new-marketing-version "$VERSION"
          agvtool new-version -all "$BUILD_NUMBER"
          
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV
          echo "ðŸ“¦ Version: $VERSION (Build: $BUILD_NUMBER)"

      - name: Install CocoaPods
        script: cd ios/App && pod install

      - name: Export Compliance
        script: |
          PLIST="ios/App/App/Info.plist"
          if /usr/libexec/PlistBuddy -c "Print :ITSAppUsesNonExemptEncryption" "$PLIST" 2>/dev/null; then
            /usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption false" "$PLIST"
          else
            /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST"
          fi
          echo "âœ… Export compliance set"

      - name: Set up code signing
        script: xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - michael@apexbiz.io
        notify:
          success: true
          failure: true
