workflows:
  tradeline_ios_testflight:
    name: TradeLine iOS → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      xcode: 16.4
      node: 22
      cocoapods: default
      groups:
        - ios_credentials
        - appstore_credentials
      vars:
        NODE_OPTIONS: "--max_old_space_size=8192"
        XCODE_SCHEME: "App"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_FALLBACK_WORKSPACE: "ios/App/App.xcodeproj/project.xcworkspace"
        INFO_PLIST_PATH: "ios/App/App/Info.plist"
        IPA_PATH: "build/ios/ipa/App.ipa"

    scripts:
      - name: Preflight (fail fast)
        script: |
          set -euo pipefail

          required_vars=(
            TEAM_ID
            BUNDLE_ID
            APP_STORE_CONNECT_ISSUER_ID
            APP_STORE_CONNECT_KEY_ID
            APP_STORE_CONNECT_PRIVATE_KEY
            CERTIFICATE_PRIVATE_KEY
          )

          for v in "${required_vars[@]}"; do
            if [ -z "${!v:-}" ]; then
              echo "Missing required env var: ${v}"
              exit 1
            fi
          done

          if [ ! -f "package.json" ]; then
            echo "package.json missing at repo root"
            exit 1
          fi

          if [ ! -f "$INFO_PLIST_PATH" ]; then
            echo "Info.plist missing at $INFO_PLIST_PATH"
            exit 1
          fi

          echo "✅ Preflight OK"

      - name: Pin npm
        script: |
          set -euo pipefail
          node -v
          npm install -g npm@10
          npm -v

      - name: Initialize keychain + fetch signing
        script: |
          set -euo pipefail

          keychain initialize

          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_ID" \
            --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY \
            --certificate-key @env:CERTIFICATE_PRIVATE_KEY

          keychain add-certificates

      - name: Install dependencies
        script: |
          set -euo pipefail
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm ci

      - name: Build web assets
        script: |
          set -euo pipefail
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm run build

      - name: Capacitor sync iOS
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: CocoaPods install
        script: |
          set -euo pipefail
          cd ios/App
          pod install
          cd ../..

      - name: Resolve workspace
        script: |
          set -euo pipefail

          if [ -d "$XCODE_WORKSPACE" ]; then
            echo "Using workspace: $XCODE_WORKSPACE"
          elif [ -d "$XCODE_FALLBACK_WORKSPACE" ]; then
            echo "XCODE_WORKSPACE=$XCODE_FALLBACK_WORKSPACE" >> "$CM_ENV"
            echo "Using fallback workspace: $XCODE_FALLBACK_WORKSPACE"
          else
            echo "❌ No workspace found. Listing ios/App:"
            ls -la ios/App || true
            exit 1
          fi

      - name: Set build number
        script: |
          set -euo pipefail

          BUILD="$(date -u +%Y%m%d%H%M%S)"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD" "$INFO_PLIST_PATH" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD" "$INFO_PLIST_PATH"

          echo "CFBundleVersion set to $BUILD"

      - name: Configure code signing
        script: |
          set -euo pipefail
          xcode-project use-profiles

      - name: Build IPA
        script: |
          set -euo pipefail
          mkdir -p build/ios/ipa

          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --ipa-path "$IPA_PATH"

      - name: Verify IPA
        script: |
          set -euo pipefail

          if [ ! -f "$IPA_PATH" ]; then
            echo "❌ IPA not found at $IPA_PATH"
            exit 1
          fi

          TEMP_DIR=$(mktemp -d)
          unzip -q "$IPA_PATH" -d "$TEMP_DIR"

          PLIST_PATH="$TEMP_DIR/Payload/App.app/Info.plist"
          if [ ! -f "$PLIST_PATH" ]; then
            echo "❌ Info.plist not found inside IPA"
            rm -rf "$TEMP_DIR"
            exit 1
          fi

          IPA_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST_PATH")
          IPA_BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_PATH")

          echo "✅ IPA Version: $IPA_VERSION"
          echo "✅ IPA Build:   $IPA_BUILD"

          rm -rf "$TEMP_DIR"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
