workflows:
  aspiral_ios_preflight:
    name: aSpiral • iOS Preflight (detect workspace/schemes)
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      groups:
        - ios_credentials
        - appstore_credentials

    scripts:
      - name: Confirm required env exists (from both groups)
        script: |
          set -euo pipefail
          for v in TEAM_ID BUNDLE_ID APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_KEY_ID APP_STORE_CONNECT_PRIVATE_KEY; do
            if [ -z "${!v:-}" ]; then
              echo "Missing required env var: $v"
              exit 1
            fi
          done
          echo "Env OK"
          echo "TEAM_ID=$TEAM_ID"
          echo "BUNDLE_ID=$BUNDLE_ID"

      - name: Repo scan (workspaces/projects/plists)
        script: |
          set -euo pipefail
          echo "=== Workspaces ==="
          find . -maxdepth 6 -name "*.xcworkspace" -print || true
          echo ""
          echo "=== Projects ==="
          find . -maxdepth 6 -name "*.xcodeproj" -print || true
          echo ""
          echo "=== Info.plist candidates ==="
          find . -maxdepth 8 -name "Info.plist" -print || true

      - name: List schemes (best-effort)
        script: |
          set -euo pipefail
          WS="$(find . -maxdepth 6 -name "*.xcworkspace" | head -n 1 || true)"
          PRJ="$(find . -maxdepth 6 -name "*.xcodeproj" | head -n 1 || true)"

          if [ -n "${WS}" ]; then
            echo "=== xcodebuild -list (workspace: ${WS}) ==="
            xcodebuild -list -workspace "${WS}" || true
          elif [ -n "${PRJ}" ]; then
            echo "=== xcodebuild -list (project: ${PRJ}) ==="
            xcodebuild -list -project "${PRJ}" || true
          else
            echo "No .xcworkspace or .xcodeproj found."
            exit 1
          fi

  aspiral_ios_testflight:
    name: aSpiral • iOS → TestFlight (ASC API key)
    max_build_duration: 90
    instance_type: mac_mini_m2

    environment:
      groups:
        - ios_credentials
        - appstore_credentials
      vars:
        # Fill these after you run preflight once
        XCODE_WORKSPACE: ""     # e.g. "./ios/App/App.xcworkspace"
        XCODE_PROJECT: ""       # e.g. "./ios/App/App.xcodeproj" (only if no workspace)
        XCODE_SCHEME: ""        # e.g. "aSpiral"
        INFO_PLIST_PATH: ""     # e.g. "./ios/App/Info.plist"

        RELEASE_VERSION: "1.0.0"

    scripts:
      - name: Preflight (fail fast)
        script: |
          set -euo pipefail

          for v in TEAM_ID BUNDLE_ID APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_KEY_ID APP_STORE_CONNECT_PRIVATE_KEY;
