import { useEffect, useState, useRef, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Share2, RotateCcw, X, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useSoundEffects } from "@/hooks/useSoundEffects";
import breakthroughIcon from "@/assets/breakthrough-icon.png";
import { useToast } from "@/hooks/use-toast";

interface BreakthroughData {
  friction: string;
  grease: string;
  insight: string;
}

interface BreakthroughCardProps {
  data: BreakthroughData | null;
  isVisible: boolean;
  onDismiss: () => void;
  onNewSession: () => void;
}

export function BreakthroughCard({ 
  data, 
  isVisible, 
  onDismiss,
  onNewSession 
}: BreakthroughCardProps) {
  const [showContent, setShowContent] = useState(false);
  const { playBreakthrough } = useSoundEffects({ enabled: true, volume: 0.6 });
  const hasPlayedSound = useRef(false);
  const { toast } = useToast();

  useEffect(() => {
    if (isVisible && data) {
      // Play breakthrough chime sound once
      if (!hasPlayedSound.current) {
        playBreakthrough();
        hasPlayedSound.current = true;
      }
      // Stagger content reveal
      const timer = setTimeout(() => setShowContent(true), 600);
      return () => clearTimeout(timer);
    } else {
      setShowContent(false);
      hasPlayedSound.current = false;
    }
  }, [isVisible, data, playBreakthrough]);

  // Generate and download breakthrough as a file
  const handleDownload = useCallback(() => {
    if (!data) return;

    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
    const timeStr = now.toLocaleTimeString('en-US', { 
      hour: '2-digit', 
      minute: '2-digit' 
    });

    const content = `# ASPIRAL Breakthrough
Generated: ${dateStr} at ${timeStr}

---

## ⚡ The Friction
${data.friction}

---

## 💧 The Grease
${data.grease}

---

## 💡 The Insight
"${data.insight}"

---

_Generated by ASPIRAL - The AI Spiral Coach_
`;

    // Create blob and trigger download
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `aspiral-breakthrough-${now.toISOString().split('T')[0]}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast({
      title: "Downloaded!",
      description: "Your breakthrough has been saved as a file.",
    });
  }, [data, toast]);

  // Copy to clipboard
  const handleCopy = useCallback(() => {
    if (!data) return;
    navigator.clipboard.writeText(
      `🔥 ${data.friction}\n💧 ${data.grease}\n💡 "${data.insight}"`
    );
    toast({
      title: "Copied!",
      description: "Breakthrough copied to clipboard.",
    });
  }, [data, toast]);

  if (!data) return null;

  return (
    <AnimatePresence>
      {isVisible && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="fixed inset-0 z-[100] bg-background/80 backdrop-blur-md"
            onClick={onDismiss}
          />

          {/* Card */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            transition={{ 
              type: "tween", 
              duration: 0.25,
              ease: "easeOut"
            }}
            className="fixed inset-2 sm:inset-4 md:inset-6 z-[101] max-w-lg mx-auto my-auto flex items-center justify-center"
          >
            <div className="relative overflow-hidden rounded-2xl sm:rounded-3xl border border-border/50 bg-gradient-to-br from-card via-card to-card/80 shadow-2xl max-h-[calc(100vh-1rem)] sm:max-h-[calc(100vh-2rem)] md:max-h-[calc(100vh-3rem)] overflow-y-auto w-full gpu-accelerated">
              {/* Glow effect - simplified */}
              <div className="absolute inset-0 bg-gradient-to-br from-primary/15 via-transparent to-secondary/15 opacity-50" />
              <div className="absolute -top-24 -right-24 h-48 w-48 rounded-full bg-primary/30 blur-3xl hidden sm:block" />
              <div className="absolute -bottom-24 -left-24 h-48 w-48 rounded-full bg-secondary/30 blur-3xl hidden sm:block" />

              {/* Close button */}
              <Button
                variant="ghost"
                size="icon"
                onClick={onDismiss}
                className="absolute top-2 right-2 sm:top-4 sm:right-4 z-10 rounded-full hover:bg-foreground/10 h-8 w-8 sm:h-10 sm:w-10"
              >
                <X className="h-4 w-4" />
              </Button>

              {/* Content */}
              <div className="relative p-4 pt-10 sm:p-6 sm:pt-12 md:p-8 md:pt-12">
                {/* Header */}
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.2 }}
                  className="text-center mb-4 sm:mb-6 md:mb-8"
                >
                  <div className="inline-flex items-center gap-1.5 sm:gap-2 px-3 py-1.5 sm:px-4 sm:py-2 rounded-full bg-primary/20 border border-primary/30 mb-2 sm:mb-4">
                    <img src={breakthroughIcon} alt="Breakthrough" className="h-4 w-4 sm:h-5 sm:w-5" />
                    <span className="text-xs sm:text-sm font-medium text-primary">BREAKTHROUGH</span>
                  </div>
                </motion.div>

                {/* Friction */}
                <AnimatePresence>
                  {showContent && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ duration: 0.15 }}
                      className="mb-4 sm:mb-6"
                    >
                      <div className="flex items-start gap-2 sm:gap-3">
                        <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 rounded-lg sm:rounded-xl bg-warning/20 border border-warning/30 flex items-center justify-center">
                          <span className="text-sm sm:text-lg">⚡</span>
                        </div>
                        <div className="min-w-0 flex-1">
                          <p className="text-[10px] sm:text-xs font-medium text-warning uppercase tracking-wider mb-0.5 sm:mb-1">The Friction</p>
                          <p className="text-sm sm:text-base text-foreground font-medium">{data.friction}</p>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Arrow */}
                <AnimatePresence>
                  {showContent && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ duration: 0.1 }}
                      className="flex justify-center my-2 sm:my-4"
                    >
                      <ArrowRight className="h-4 w-4 sm:h-5 sm:w-5 text-muted-foreground rotate-90" />
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Grease */}
                <AnimatePresence>
                  {showContent && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ duration: 0.15 }}
                      className="mb-4 sm:mb-6"
                    >
                      <div className="flex items-start gap-2 sm:gap-3">
                        <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 rounded-lg sm:rounded-xl bg-accent/20 border border-accent/30 flex items-center justify-center">
                          <span className="text-sm sm:text-lg">💧</span>
                        </div>
                        <div className="min-w-0 flex-1">
                          <p className="text-[10px] sm:text-xs font-medium text-accent uppercase tracking-wider mb-0.5 sm:mb-1">The Grease</p>
                          <p className="text-sm sm:text-base text-foreground font-medium">{data.grease}</p>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Insight */}
                <AnimatePresence>
                  {showContent && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ duration: 0.2 }}
                      className="mt-4 sm:mt-6 md:mt-8 p-4 sm:p-6 rounded-xl sm:rounded-2xl bg-gradient-to-br from-primary/10 via-secondary/10 to-primary/5 border border-primary/20"
                    >
                      <p className="text-[10px] sm:text-xs font-medium text-secondary uppercase tracking-wider mb-2 sm:mb-3 text-center">💡 The Insight</p>
                      <p className="text-base sm:text-lg font-display font-semibold text-center text-foreground leading-relaxed">
                        "{data.insight}"
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Actions */}
                <AnimatePresence>
                  {showContent && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ duration: 0.2 }}
                      className="flex flex-wrap items-center justify-center gap-2 sm:gap-3 mt-4 sm:mt-6 md:mt-8"
                    >
                      <Button
                        variant="outline"
                        size="sm"
                        className="rounded-lg sm:rounded-xl gap-1.5 sm:gap-2 text-xs sm:text-sm h-8 sm:h-9 px-2.5 sm:px-3"
                        onClick={handleCopy}
                      >
                        <Share2 className="h-3 w-3 sm:h-3.5 sm:w-3.5" />
                        Copy
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        className="rounded-lg sm:rounded-xl gap-1.5 sm:gap-2 text-xs sm:text-sm h-8 sm:h-9 px-2.5 sm:px-3"
                        onClick={handleDownload}
                      >
                        <Download className="h-3 w-3 sm:h-3.5 sm:w-3.5" />
                        Download
                      </Button>
                      <Button
                        size="sm"
                        className="rounded-lg sm:rounded-xl gap-1.5 sm:gap-2 bg-gradient-to-r from-primary to-secondary text-xs sm:text-sm h-8 sm:h-9 px-2.5 sm:px-3"
                        onClick={onNewSession}
                      >
                        <RotateCcw className="h-3 w-3 sm:h-3.5 sm:w-3.5" />
                        New Spiral
                      </Button>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
